[project]
name = "02806-social-graph-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kirk", email = "s224225@dtu.dk" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
02806-social-graph-project = "02806_social_graph_project:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
