[project]
name = "02806-social-graph-project"
version = "0.1.0"
description = "02805 group site and weekly go-nuts posts"
readme = "README.md"
authors = [
    { name = "Kirk", email = "s224225@dtu.dk" }
]
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.6.1",
]

[tool.uv]
package = false
